### ISSUE TITLE
Publishing on PyPI

### ISSUE THREAD

**Issue by acdha** [unt-libraries/pycallnumber#18]
Is there a plan to publish this on PyPI? A lot of tooling for deployment, security scans, etc. would benefit from this being a simple pip install away.

**Comment by jthomale** [comment]
Yes! Definitely. Thank you for raising this issue&mdash;it was on my to-do list at one point but fell off without getting done. It is now officially on my to-do list. :smile:

**Comment by acdha** [comment]
Awesome!

**Comment by jthomale** [comment]
Pycallnumber is now on PyPI and can be installed via a simple `pip install pycallnumber` command. Trying it out on a RedHat box running Python 2.7.5, I noticed I had to upgrade pip first before pycallnumber would install. (It initially complained about an outdated setuptools.) I think that's probably normal though. Thanks again for putting this task back on my radar!

**Comment by acdha** [comment]
Awesome!
